config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users/courses/:id', to: 'users#my_courses', as: 'mycourses'

  resources :users, only: [:show]
  resources :courses

  resources :categories
  resources :subcategories
  resources :subsubcategories

  namespace :api do
    namespace :v1 do
      resource :courses, only: [:index, :create, :destroy, :update, :show]
      resource :categories
      resource :subcategories do
        get ':id', to: 'subcategories#item'
      end

      resource :subsubcategories do
      get ':id', to: 'subsubcategories#item'
    end
    end
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category

  has_many :courses
  has_many :subsubcategories, dependent: :destroy

  validates :name, presence: true
end

app/controllers/api/v1/subcategories_controller.rb
class Api::V1::SubcategoriesController < ApplicationController
  def index
    # render json: Subcategory.all
  end

  def create
    subcategory = Subcategory.create(subcategory_params)
    render json: subcategory
  end

  def destroy
    Subcategory.destroy(params[:id])
  end

  def update
    subcategory = Subcategory.find(params[:id])
    subcategory.update_attributes(subcategory_params)
    render json: subcategory
  end

  def show
    # render json: Subcategory.all.order('name asc')
  end
  def item
    render json: Subcategory.where(category_id: params[:id])
  end

  private

    def subcategory_params
      params.require(:subcategory).permit(:id, :name)
    end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_category, only: [:destroy, :show, :edit, :update]
  def index
    @subcategory = Subcategory.all
  end
  def show
    @courses = Course.where(subcategory_id: params[:id]).order("updated_at DESC")
  end
  def new
    @subcategory = Subcategory.new
    @categories = Category.all.order(:name)
  end
  def create
    @subcategory = Subcategory.new(subcategory_params)
    if @subcategory.save
      redirect_to @subcategory
    else
      @categories = Category.all.order(:name)
      render :new
    end
  end
  def edit
    @categories = Category.all.order(:name)
  end
  def update
    if @subcategory.update_attributes(subcategory_params)
      redirect_to @subcategory
    else
      @categories = Category.all.order(:name)
      render :edit
    end
  end
  def destroy
    @subcategory.destroy
    redirect_to subcategories_path
  end

  protected
    def set_category
      @subcategory = Subcategory.find(params[:id])
    end

    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.haml
= form_for @subcategory, html: {class: 'ui form'} do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category_id
    = f.collection_select :category_id, @categories, :id, :name, { include_blank: true}
  = f.submit "submit", class: 'ui button green'

app/views/subcategories/index.html.haml
= link_to "новая категория", new_subcategory_path, class: 'ui button yellow'

%table.ui.celled.table
  %thead
    %tr
      %th parent
      %th название
      %th
  %tbody
    - @subcategory.each do |subcategory|
      %tr
        %th= subcategory.category.name
        %th
          = link_to subcategory.name, subcategory_path(subcategory)
        %th
          =link_to "изменить", edit_subcategory_path(subcategory), class: 'ui button blue'
          =link_to "удалить", subcategory_path(subcategory), method: :delete, class: 'ui button blue'

app/views/subcategories/show.html.haml
= @subcategory.name
= @subcategory.category.name