config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users/courses/:id', to: 'users#my_courses', as: 'mycourses'

  resources :users, only: [:show]
  resources :courses

  resources :categories
  resources :subcategories
  resources :subsubcategories

  namespace :api do
    namespace :v1 do
      resource :courses, only: [:index, :create, :destroy, :update, :show]
      resource :categories
      resource :subcategories do
        get ':id', to: 'subcategories#item'
      end

      resource :subsubcategories do
      get ':id', to: 'subsubcategories#item'
    end
    end
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subsubcategory.rb
class Subsubcategory < ApplicationRecord
  belongs_to :subcategory

  has_many :courses
  validates :name, presence: true
end

app/controllers/api/v1/subsubcategories_controller.rb
class Api::V1::SubsubcategoriesController < ApplicationController
  def index
    render json: Category.all
  end

  def create
    subsubcategory = Subsubcategory.create(subsubcategory_params)
    render json: subsubcategory
  end

  def destroy
    Subsubcategory.destroy(params[:id])
  end

  def update
    subsubcategory = Subsubcategory.find(params[:id])
    subsubcategory.update_attributes(subsubcategory_params)
    render json: subsubcategory
  end

  def show
    # render json: Subsubcategory.all
  end
  def item
    render json: Subsubcategory.where(subcategory_id: params[:id])
  end
  private

    def subsubcategory_params
      params.require(:subsubcategory).permit(:id, :name)
    end
end

app/controllers/subsubcategories_controller.rb
class SubsubcategoriesController < ApplicationController
  before_action :set_category, only: [:destroy, :show, :edit, :update]
  def index
    @subsubcategory = Subsubcategory.all
  end
  def show
    @courses = Course.where(subsubcategory_id: params[:id]).order("updated_at DESC")
  end
  def new
    @subsubcategory = Subsubcategory.new
    @subcategories = Subcategory.all.order(:name)
  end
  def create
    @subsubcategory = Subsubcategory.new(subsubcategory_params)
    if @subsubcategory.save
      redirect_to @subsubcategory
    else
      @subcategories = Subcategory.all.order(:name)
      render :new
    end
  end
  def edit
    @subcategories = Subcategory.all.order(:name)
  end
  def update
    if @subsubcategory.update_attributes(subsubcategory_params)
      redirect_to @subsubcategory
    else
      @subcategories = Subcategory.all.order(:name)
      render :edit
    end
  end
  def destroy
    @subsubcategory.destroy
    redirect_to subsubcategories_path
  end

  protected
    def set_category
      @subsubcategory = Subsubcategory.find(params[:id])
    end

    def subsubcategory_params
      params.require(:subsubcategory).permit(:name, :subcategory_id)
    end
end

app/views/subsubcategories/_form.html.haml
= form_for @subsubcategory, html: {class: 'ui form'} do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :subcategory_id
    = f.collection_select :subcategory_id, @subcategories, :id, :name, { include_blank: true}
  = f.submit "submit", class: 'ui button green'

app/views/subsubcategories/edit.html.haml
%h1 редактировать
= render 'form'

app/views/subsubcategories/index.html.haml
= link_to "новая категория", new_subsubcategory_path, class: 'ui button yellow'

%table.ui.celled.table
  %thead
    %tr
      %th parent
      %th название
      %th
  %tbody
    - @subsubcategory.each do |subsubcategory|
      %tr
        %th= subsubcategory.subcategory.name
        %th
          = link_to subsubcategory.name, subsubcategory_path(subsubcategory)
        %th
          =link_to "изменить", edit_subsubcategory_path(subsubcategory), class: 'ui button blue'
          =link_to "удалить", subsubcategory_path(subsubcategory), method: :delete, class: 'ui button blue'

app/views/subsubcategories/new.html.haml
%h1  создать
= render 'form'

app/views/subsubcategories/show.html.haml
= @subsubcategory.name
= @subsubcategory.subcategory.name