config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users/courses/:id', to: 'users#my_courses', as: 'mycourses'

  resources :users, only: [:show]
  resources :courses

  resources :categories
  resources :subcategories
  resources :subsubcategories

  namespace :api do
    namespace :v1 do
      resource :courses, only: [:index, :create, :destroy, :update, :show]
      resource :categories
      resource :subcategories do
        get ':id', to: 'subcategories#item'
      end

      resource :subsubcategories do
      get ':id', to: 'subsubcategories#item'
    end
    end
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses
  has_many :subcategories, dependent: :destroy
  validates :name, presence: true
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
  def index
    render json: Category.all
  end

  def create
    category = Category.create(category_params)
    render json: category
  end

  def destroy
    Category.destroy(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update_attributes(category_params)
    render json: category
  end

  def show
    render json: Category.all.order('name ASC')
  end
  private

    def category_params
      params.require(:category).permit(:id, :name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:destroy, :show, :edit, :update]
  def index
    @categories = Category.all
    # @subcategories = Subcategory.find(params[:id])
  end
  def show
    @courses = Course.where(category_id: params[:id]).order("updated_at DESC")
  end
  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      @categories = Category.all.order(:name)
      render :new
    end
  end
  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end
  def update
    if @category.update_attributes(category_params)
      redirect_to @category
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      render :edit
    end
  end
  def destroy
    @category.destroy
    redirect_to categories_path
  end

  protected
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_course.html.haml
.item
  %a.ui.small.image{:href => "#{course_path(course)}"}
    = image_tag "https://semantic-ui.com/images/avatar2/large/kristy.png"
  .content
    - if course.c_username.present?
      = link_to course.c_username, course_path(course)
    .meta
      - if course.price.present?
        цена:
        = course.price
      - if course.category.present?
        = link_to course.category.name, course.category

    - if course.body.present?
      .description
        = course.body

app/views/categories/_form.html.haml
= form_for @category, html: {class: 'ui form'} do |f|
  .field
    = f.label :name
    = f.text_field :name

  = f.submit "submit", class: 'ui button green'

app/views/categories/index.html.haml
= link_to "новая категория", new_category_path, class: 'ui button yellow'
%table.ui.celled.table
  %thead
    %tr
      %th индекс
      %th название
      %th
  %tbody
    - @categories.each_with_index do |category, index|
      %tr
        %th= index + 1
        %th
          = link_to category.name, category_path(category)
        %th
          =link_to "изменить", edit_category_path(category), class: 'ui button blue'
          =link_to "удалить", category_path(category), method: :delete, class: 'ui button blue'

app/views/categories/show.html.haml
= link_to "новая категория", new_subcategory_path, class: 'ui button yellow'

- if @courses.any?
  .ui.items
    = render @courses