config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users/courses/:id', to: 'users#my_courses', as: 'mycourses'

  resources :users, only: [:show]
  resources :courses

  resources :categories
  resources :subcategories
  resources :subsubcategories

  namespace :api do
    namespace :v1 do
      resource :courses, only: [:index, :create, :destroy, :update, :show]
      resource :categories
      resource :subcategories do
        get ':id', to: 'subcategories#item'
      end

      resource :subsubcategories do
      get ':id', to: 'subsubcategories#item'
    end
    end
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.haml
.ui.secondary.menu
  = link_to "главаная", root_path, class: 'ui button red'
  = link_to "Обьявления", courses_path, class: 'ui button orange'
  = link_to "Категории", categories_path, class: 'ui button orange'
  = link_to "Под категории", subcategories_path, class: 'ui button orange'
  = link_to "Под под категории", subsubcategories_path, class: 'ui button orange'
  .right.menu
    - if user_signed_in?
      = link_to "#{current_user.username if current_user.username.present?}", user_path(current_user), class: 'ui button blue'
      = link_to "Выход", destroy_user_session_path, method: :delete, class: 'ui button blue'
    -else
      = link_to "Вход", new_user_session_path, class: 'ui button green'
    = link_to "создать обьявление", new_course_path, class: 'ui button orange'


-#    <a href="tasks.html" class="ui button blue">просмотреть задания</a>
-#    <a href="new_task.html" class="ui button blue">создать задание</a>

-#    <a href="profile.html" class="ui item">Профиль</a>
-#    <a class="ui item">язык</a>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title filter
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
  %body
    = render 'layouts/menu'

    %p.notice= notice
    %p.alert= alert

    .ui.container
      = yield